// ==UserScript==
// @name          White-Off for Logos Community Forums
// @namespace     http://userstyles.org
// @description	  An easier to read, modernized theme for Logos' Forums. It's not a dark theme, but instead eliminates white and other bright colors and uses color selections that reduce contrast. It's not designed to pop and wow like most sites, but tries to relax and ease eye strain.
// @author        Randy W. Sims (Shayne)
// @homepage      https://userstyles.org/styles/158383
// @include       http://community.logos.com/*
// @include       https://community.logos.com/*
// @include       http://*.community.logos.com/*
// @include       https://*.community.logos.com/*
// @run-at        document-start
// @version       0.9.1
// ==/UserScript==
(function() {var css = [
	"/*! Font Awesome Free 5.1.0 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License) */",
	"  .fa, .fas, .defaultSkin .mceSplitButton span.mceAction, .defaultSkin .mceIcon, #CommonHeaderUserWelcome .sub a[href*=\"EditProfile.aspx\"]::before, #CommonHeaderUserWelcome .sub a[href$=\"logout.aspx\"]::before, ul.CommonContentBoxList li.CommonActivity table tr td + td a::after, ul.CommonContentBoxList li.CommonActivity.NewForumThread td:first-child::before, ul.CommonContentBoxList li.CommonActivity.NewForumPost td:first-child::before, .far, .fal, .fab { -moz-osx-font-smoothing: grayscale; -webkit-font-smoothing: antialiased; display: inline-block; font-style: normal; font-variant: normal; text-rendering: auto; line-height: 1; }",
	"  @font-face { font-family: \'Font Awesome 5 Free\'; font-style: normal; font-weight: 900; src: url(\"https://use.fontawesome.com/releases/v5.1.0/webfonts//fa-solid-900.eot\"); src: url(\"https://use.fontawesome.com/releases/v5.1.0/webfonts//fa-solid-900.eot?#iefix\") format(\"embedded-opentype\"), url(\"https://use.fontawesome.com/releases/v5.1.0/webfonts//fa-solid-900.woff2\") format(\"woff2\"), url(\"https://use.fontawesome.com/releases/v5.1.0/webfonts//fa-solid-900.woff\") format(\"woff\"), url(\"https://use.fontawesome.com/releases/v5.1.0/webfonts//fa-solid-900.ttf\") format(\"truetype\"), url(\"https://use.fontawesome.com/releases/v5.1.0/webfonts//fa-solid-900.svg#fontawesome\") format(\"svg\"); }",
	"  .fa, .fas, .defaultSkin .mceSplitButton span.mceAction, .defaultSkin .mceIcon, #CommonHeaderUserWelcome .sub a[href*=\"EditProfile.aspx\"]::before, #CommonHeaderUserWelcome .sub a[href$=\"logout.aspx\"]::before, ul.CommonContentBoxList li.CommonActivity table tr td + td a::after, ul.CommonContentBoxList li.CommonActivity.NewForumThread td:first-child::before, ul.CommonContentBoxList li.CommonActivity.NewForumPost td:first-child::before { font-family: \'Font Awesome 5 Free\'; font-weight: 900; }",
	"  @font-face { font-family: \'Font Awesome 5 Brands\'; font-style: normal; font-weight: normal; src: url(\"https://use.fontawesome.com/releases/v5.1.0/webfonts//fa-brands-400.eot\"); src: url(\"https://use.fontawesome.com/releases/v5.1.0/webfonts//fa-brands-400.eot?#iefix\") format(\"embedded-opentype\"), url(\"https://use.fontawesome.com/releases/v5.1.0/webfonts//fa-brands-400.woff2\") format(\"woff2\"), url(\"https://use.fontawesome.com/releases/v5.1.0/webfonts//fa-brands-400.woff\") format(\"woff\"), url(\"https://use.fontawesome.com/releases/v5.1.0/webfonts//fa-brands-400.ttf\") format(\"truetype\"), url(\"https://use.fontawesome.com/releases/v5.1.0/webfonts//fa-brands-400.svg#fontawesome\") format(\"svg\"); }",
	"  .fab { font-family: \'Font Awesome 5 Brands\'; }",
	"  @font-face { font-family: \"Source Sans Pro\"; font-style: normal; font-weight: 300; src: local(\"Source Sans Pro Light\"), local(\"SourceSansPro-Light\"), url(https://fonts.gstatic.com/s/sourcesanspro/v11/6xKydSBYKcSV-LCoeQqfX1RYOo3ik4zwlxdu.woff2) format(\"woff2\"); unicode-range: U+0000-00FF; }",
	"  html, body { background-image: none; background-color: #c3c3c3; color: black; font-family: -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, Oxygen-Sans, Ubuntu, Cantarell, \"Helvetica Neue\", sans-serif; }",
	"  blockquote { box-shadow: 0 2px 2px 0 rgba(0, 0, 0, 0.14), 0 3px 1px -2px rgba(0, 0, 0, 0.2), 0 1px 5px 0 rgba(0, 0, 0, 0.12); quotes: \"\\201c\" \"\\201d\"; background-color: #f8e8d7; border: none; border-radius: 5px; margin: 1em 2em 1em 1em; padding: .5em 1em 1em 1em; }",
	"  a:link, a:active, a:visited { color: #005ec4; text-decoration: none; font-weight: 500; }",
	"  a:hover { color: #c46600; text-decoration: underline; }",
	"  select, textarea, input, button { background-color: #fcf7f2; border-radius: 4px !important; color: #333; font-family: -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, Oxygen-Sans, Ubuntu, Cantarell, \"Helvetica Neue\", sans-serif; margin: 2px 4px; padding: 2px 4px; letter-spacing: .1em; white-space: normal !important; }",
	"  select { -webkit-appearance: none; -moz-appearance: none; appearance: none; background: url(\"data:image/svg+xml,%3Csvg xmlns=\'http://www.w3.org/2000/svg\' aria-hidden=\'true\' data-prefix=\'fas\' data-icon=\'caret-down\' class=\'svg-inline--fa fa-caret-down fa-w-10\' width=\'10.577\' height=\'6\'%3E%3Cpath d=\'M.712 0h9.154a.71.71 0 0 1 .501 1.213L5.792 5.792a.713.713 0 0 1-1.007 0L.21 1.213A.71.71 0 0 1 .712 0z\' fill=\'%23777\' stroke-width=\'.036\'/%3E%3C/svg%3E\") calc(100% - 10px) no-repeat #fcf7f2; border: none; border: solid 1px #777; padding: 4px 32px 4px 16px; }",
	"  label { letter-spacing: .1em; }",
	"  label > input { margin-right: 4px !important; }",
	"  button, [type=\'button\'], [type=\'reset\'], [type=\'submit\'] { display: inline-block; border: 1px solid #777; border-radius: 4px !important; padding: .5em 1em; margin: .5em .25em; text-decoration: none; background: linear-gradient(to bottom, silver 0%, #a0a0a0 80%, #909090 100%); color: #333; font-family: -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, Oxygen-Sans, Ubuntu, Cantarell, \"Helvetica Neue\", sans-serif; font-weight: 500; font-size: 1em; line-height: 1; cursor: pointer; text-align: center; -webkit-appearance: none; -moz-appearance: none; min-width: 80px; }",
	"  body > div#content { box-shadow: 0 2px 2px 0 rgba(0, 0, 0, 0.14), 0 3px 1px -2px rgba(0, 0, 0, 0.2), 0 1px 5px 0 rgba(0, 0, 0, 0.12); background-color: #fcf7f2; padding: 20px; }",
	"  body > div#content::before { position: absolute; left: 0; top: 0; width: 100%; height: 100%; content: \"\"; background-color: #c3c3c3; z-index: -1; }",
	"  body > div#content h2 { color: #c46600; }",
	"  .CommonMessageSuccess { color: black; border: solid 1px black; background-color: #ffebb4; }",
	"  .CommonMessageWarning { color: black; border: solid 1px black; background-color: #ffebb4; }",
	"  .CommonMessageError { color: black; border: solid 1px black; background-color: #d66; }",
	"  .Normal .CommonCommentUser { width: 100px; }",
	"  .ForumPostUserAvatar { padding: 14px 0 4px 0; }",
	"  .ForumPostUserAvatar a { display: block; }",
	"  .ForumPostUserAvatar img { display: block; margin: 0 auto; border-radius: 4px; background-color: white; transition: -webkit-transform 0.4s ease-in-out; transition: transform 0.4s ease-in-out; transition: transform 0.4s ease-in-out, -webkit-transform 0.4s ease-in-out; z-index: 1; }",
	"  .ForumPostUserAvatar img:hover { box-shadow: 0 8px 10px 1px rgba(0, 0, 0, 0.14), 0 3px 14px 2px rgba(0, 0, 0, 0.12), 0 5px 5px -3px rgba(0, 0, 0, 0.2); transform: scale(2) translate(26px, 18px); position: absolute; }",
	"  .ForumPostRoleIcons br { display: none; }",
	"  .ForumPostRoleIcons a { display: block; position: relative; margin-top: 4px; width: 100%; height: 24px; background-repeat: no-repeat; background-size: 24px auto; background-position-x: center; }",
	"  .ForumPostRoleIcons img[alt=\'Forum MVP\'] { display: none; }",
	"  .ForumPostRoleIcons a[href*=\"82cdfc90-c0bd-4207-bf1e-13b8938a9601\"] { background-image: url(\"data:image/svg+xml,%3Csvg xmlns=\'http://www.w3.org/2000/svg\' width=\'33.699\' height=\'32\'%3E%3Cpath d=\'M6.513 32L16.85 0l10.336 32L0 12.177h33.7z\' fill=\'%23DAA520\' stroke-width=\'.142\'/%3E%3C/svg%3E\"); filter: drop-shadow(0 0 1px #987316); }",
	"  .ForumPostRoleIcons a[href*=\"82cdfc90-c0bd-4207-bf1e-13b8938a9601\"]:hover::after { display: block; position: absolute; background: rgba(0, 0, 0, 0.8); padding: .3em 1em; border-radius: .5em; top: -3.75em; left: 0.5em; width: 65%; color: #fff; text-shadow: 0 1px 0 black; text-decoration: none; white-space: normal; z-index: 1000; content: \"MVP Volunteer\"; }",
	"  .ForumPostRoleIcons img[alt=\'RIP\'] { display: none; }",
	"  .ForumPostRoleIcons a[href*=\"6388d75f-2687-441f-a94e-e966f273121e\"] { /* https://www.etsy.com/shop/VectorartDesigns - Bird Dove Animal */ background-image: url(\"data:image/svg+xml,%3Csvg xmlns=\'http://www.w3.org/2000/svg\' width=\'99.449\' height=\'120.945\' viewBox=\'0 0 26.313 32\'%3E%3Cpath d=\'M11.645 9.064C4.376 6.247 5.636 1.338 5.636.079c0-.195-.175-.021-.426.43-1.193 1.786-5.609 13.413 4.652 21.46l-.205-.492C1.054 13.84 3.6 4.504 5.133 1.092c-.14 1.77-.43 5.933 6.043 8.441 6.432 2.492 6.632 6.36 6.593 7.218l.455-.29s.69-4.58-6.579-7.397zm13.926 6.629l.742-.398s-4.033.897-4.477 4.585c-.523 3.626-4.865 6.643-9.644 5.982-4.78-.662-5.374 1.6-5.377 2.304-.005 1.491.5 3.405-2.219 3.065 0 0-1.705-.213-3.431-2.007.93 2.191 3.9 2.74 3.9 2.74 2.728.397 2.234-2.617 2.22-3.328-.021-1.018.597-2.966 5.376-2.305 4.78.662 9.208-2.476 9.645-5.981.43-3.452 3.265-4.657 3.265-4.657zm-.151-.676s-1.764-3.03-5.48-.932c0 0 1.821-2.248.825-5.99-.995-3.74-2.332-6.272-1.166-7.823 0 0-.203.22-.521.569-1.047 1.558.242 4.057 1.218 7.724.996 3.741-.825 5.989-.825 5.989 4.02-2.054 5.949.463 5.949.463zM17.41 2.165c.14-.375.153-.18-.039-.28 0 0-3.755 2.08-4.068 6.417 0 0 .502-.307.675-.791.65-2.668 2.569-4.744 3.432-5.346zM8.648 21.872s-5.32 1.214-6.234-.525c-.636-1.21-1.89.172-2.181 1.49-.316 1.741-.392 2.807.3 4.747-.482-1.791-.205-3.691-.097-4.247.202-1.057 1.098-2.645 1.749-1.554 1.177 1.778 6.463.09 6.463.09zm13.126-6.53c.362 0 .362-.55 0-.55s-.362.55 0 .55z\' class=\'fil0\' clip-rule=\'evenodd\' stroke-width=\'0\' fill=\'%23B8860B\' image-rendering=\'optimizeQuality\' shape-rendering=\'geometricPrecision\' text-rendering=\'geometricPrecision\'/%3E%3C/svg%3E\"); filter: drop-shadow(0 0 1px #805d07); background-size: 36px auto; height: 48px; }",
	"  .ForumPostRoleIcons a[href*=\"6388d75f-2687-441f-a94e-e966f273121e\"]:hover::after { display: block; position: absolute; background: rgba(0, 0, 0, 0.8); padding: .3em 1em; border-radius: .5em; top: -3.75em; left: 0.5em; width: 65%; color: #fff; text-shadow: 0 1px 0 black; text-decoration: none; white-space: normal; z-index: 1000; content: \"Requiescat in pace\"; }",
	"  .ForumPostRoleIcons img[alt=\'LogosEmployee\'] { display: none; }",
	"  .ForumPostRoleIcons a[href*=\"a908d13f-b28a-41d9-ad6f-a58d54987218\"] { background-image: url(\"data:image/svg+xml,%3Csvg xmlns=\'http://www.w3.org/2000/svg\' width=\'32\' height=\'54.489\' viewBox=\'0 0 8.467 14.417\'%3E%3Cg fill=\'%235FBC39\' fill-rule=\'evenodd\'%3E%3Cpath d=\'M4.75 14.399a.028.028 0 0 1-.048.008 18.377 18.377 0 0 0-3.082-2.635C.628 11.07.24 10.635.127 10.494c-.015-.019 0-.048.024-.047.115.007.383.017.721-.006.023-.001.034-.025.023-.044C.749 10.174.05 9.061 0 7.815c0-.023.023-.037.042-.027.106.06.395.213.764.322.02.006.04-.012.036-.033C.786 7.817.54 6.515.789 5.195a.029.029 0 0 1 .05-.015c.073.082.258.263.584.452.015.009.034.002.04-.015.08-.228.583-1.609 1.434-2.437.016-.016.044-.006.047.017.372 2.441 2.481 2.998 3.478 5.148.67 1.442-.178 2.235-.456 2.446-.024.017-.01.054.02.052 1.59-.129 2.25-1.57 2.422-2.03.011-.03.054-.022.055.01.112 3.4-2.65 3.6-3.087 3.614a.215.215 0 0 1-.106-.025c-2.496-1.33-2.484-3.983-2.458-4.485 0-.015-.021-.02-.027-.006-1.255 3.033.905 4.747 1.675 5.497.309.3.445.567.288.981\'/%3E%3Cpath d=\'M5.13.01c.02-.022.057-.006.053.025a5.268 5.268 0 0 0 1.38 4.111c1.757 1.894 1.566 3.338.94 4.679-.015.03-.06.02-.06-.014.012-.362-.087-1.11-1.31-2.463C4.196 4.208 2.838 2.632 5.13.01\'/%3E%3C/g%3E%3C/svg%3E\"); background-size: 18px auto; height: 32px; }",
	"  .ForumPostRoleIcons a[href*=\"a908d13f-b28a-41d9-ad6f-a58d54987218\"]:hover::after { display: block; position: absolute; background: rgba(0, 0, 0, 0.8); padding: .3em 1em; border-radius: .5em; top: -3.75em; left: 0.5em; width: 65%; color: #fff; text-shadow: 0 1px 0 black; text-decoration: none; white-space: normal; z-index: 1000; content: \"Faithlife Employee\"; }",
	"  .ForumPostRoleIcons a[href*=\"25ecb0d8-f993-4c33-accd-1b5432861991\"]:hover::after { display: block; position: absolute; background: rgba(0, 0, 0, 0.8); padding: .3em 1em; border-radius: .5em; top: -5em; left: 0.5em; width: 65%; color: #fff; text-shadow: 0 1px 0 black; text-decoration: none; white-space: normal; z-index: 1000; content: \"Morris Proctor Employee\"; }",
	"  .CommonTextButton { color: #e39c4f; }",
	"  .ReplyButton, .MoreButton { box-shadow: 0 2px 2px 0 rgba(0, 0, 0, 0.14), 0 3px 1px -2px rgba(0, 0, 0, 0.2), 0 1px 5px 0 rgba(0, 0, 0, 0.12); background-image: none; background-color: #e39c4f; border-radius: 1em; margin: 0 2px; padding: .1em .5em .1em .5em; opacity: 0.85; transition-duration: 0.3s; width: 60px; }",
	"  .ReplyButton:link, .ReplyButton:visited, .MoreButton:link, .MoreButton:visited { box-shadow: 0 2px 2px 0 rgba(0, 0, 0, 0.14), 0 3px 1px -2px rgba(0, 0, 0, 0.2), 0 1px 5px 0 rgba(0, 0, 0, 0.12); transition: all .1s; }",
	"  .ReplyButton:hover, .MoreButton:hover { box-shadow: 0 4px 5px 0 rgba(0, 0, 0, 0.14), 0 1px 10px 0 rgba(0, 0, 0, 0.12), 0 2px 4px -1px rgba(0, 0, 0, 0.2); opacity: 1; transform: translateY(-1px); }",
	"  .ReplyButton:active, .MoreButton:active { transform: translateY(1px); box-shadow: none; }",
	"  .ReplyButton a:hover, .MoreButton a:hover { text-decoration: none; }",
	"  .ReplyButton span, .MoreButton span { color: #333; padding: .1em .1em .1em .2em; text-align: center; width: auto; }",
	"  .ReplyButton span font, .MoreButton span font { margin-left: .25em; }",
	"  .Editor .CommonFormArea > .CommonFormFieldName > strong { font-size: 20px; text-shadow: 0 2px 2px rgba(0, 0, 0, 0.14); }",
	"  .CommonFormArea > .CommonFormFieldName > label[for=\"ctl00_bcr_PostForm_ctl05_PostBody\"] { font-size: 20px; text-shadow: 0 2px 2px rgba(0, 0, 0, 0.14); }",
	"  .defaultSkin table.mceLayout { border: 1px solid #999 !important; }",
	"  .defaultSkin table.mceLayout tr.mceFirst td { border: none !important; }",
	"  .defaultSkin table.mceLayout tr.mceLast td { border: none !important; }",
	"  .defaultSkin td.mceToolbar { padding: 4px 2px; background: linear-gradient(to bottom, silver 0%, #a0a0a0 80%, #909090 100%) !important; }",
	"  .defaultSkin td.mceStatusbar { background: linear-gradient(to bottom, silver 0%, #a0a0a0 80%, #909090 100%) !important; }",
	"  .defaultSkin .mceListBox .mceText { Width: 60px; margin-left: 2px; }",
	"  #ctl00_bcr_EditUserForm1_ctl02_Signature_ctl00_Editor_fontselect_text, #ctl00_bcr_PostForm_ctl05_PostBody_ctl00_Editor_fontselect_text, #ctl00_ctl00_bcr_bcr_PostForm_ctl05_PostBody_ctl00_Editor_fontselect_text { Width: 100px; }",
	"  .defaultSkin .mceButton { border: 1px solid transparent !important; width: 20px !important; height: 20px !important; margin: 2px !important; padding: 2px !important; }",
	"  .defaultSkin .mceSplitButton span.mceAction { -webkit-font-smoothing: antialiased; -moz-osx-font-smoothing: grayscale; display: inline-block; font-style: normal; font-variant: normal; font-weight: normal; line-height: 1; vertical-align: -.125em; height: 18px !important; background: none !important; }",
	"  .defaultSkin .mceIcon { -webkit-font-smoothing: antialiased; -moz-osx-font-smoothing: grayscale; display: inline-block; font-style: normal; font-variant: normal; font-weight: normal; line-height: 1; vertical-align: -.125em; background: none !important; width: 20px !important; height: 20px !important; padding-top: 2px !important; }",
	"  .defaultSkin img.mceIcon { display: none !important; }",
	"  .defaultSkin .mceSeparator { margin: 2px 4px 0 4px !important; }",
	"  .defaultSkin .mceListBox .mceText { font-family: -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, Oxygen-Sans, Ubuntu, Cantarell, \"Helvetica Neue\", sans-serif !important; letter-spacing: .02em !important; }",
	"  .defaultSkin span.mce_forecolor { background-position: unset !important; text-align: center !important; }",
	"  .defaultSkin span.mce_forecolor::before { content: \"\\f031\"; color: #333 !important; font-size: 16px !important; width: 20px !important; height: 20px !important; }",
	"  .defaultSkin span.mce_backcolor { background-position: unset !important; text-align: center !important; }",
	"  .defaultSkin span.mce_backcolor::before { content: \"\\f53f\"; color: #333 !important; font-size: 16px !important; width: 20px !important; height: 20px !important; }",
	"  .defaultSkin span.mce_cut { background-position: unset !important; text-align: center !important; }",
	"  .defaultSkin span.mce_cut::before { content: \"\\f0c4\"; color: #333 !important; font-size: 16px !important; width: 20px !important; height: 20px !important; }",
	"  .defaultSkin span.mce_copy { background-position: unset !important; text-align: center !important; }",
	"  .defaultSkin span.mce_copy::before { content: \"\\f0c5\"; color: #333 !important; font-size: 16px !important; width: 20px !important; height: 20px !important; }",
	"  .defaultSkin span.mce_paste { background-position: unset !important; text-align: center !important; }",
	"  .defaultSkin span.mce_paste::before { content: \"\\f0ea\"; color: #333 !important; font-size: 16px !important; width: 20px !important; height: 20px !important; }",
	"  .defaultSkin span.mce_pasteword { background-position: unset !important; text-align: center !important; }",
	"  .defaultSkin span.mce_pasteword::before { content: \"\\f1c2\"; color: #333 !important; font-size: 16px !important; width: 20px !important; height: 20px !important; }",
	"  .defaultSkin span.mce_code { background-position: unset !important; text-align: center !important; }",
	"  .defaultSkin span.mce_code::before { content: \"\\f121\"; color: #333 !important; font-size: 16px !important; width: 20px !important; height: 20px !important; }",
	"  .defaultSkin span.mce_bold { background-position: unset !important; text-align: center !important; }",
	"  .defaultSkin span.mce_bold::before { content: \"\\f032\"; color: #333 !important; font-size: 16px !important; width: 20px !important; height: 20px !important; }",
	"  .defaultSkin span.mce_italic { background-position: unset !important; text-align: center !important; }",
	"  .defaultSkin span.mce_italic::before { content: \"\\f033\"; color: #333 !important; font-size: 16px !important; width: 20px !important; height: 20px !important; }",
	"  .defaultSkin span.mce_underline { background-position: unset !important; text-align: center !important; }",
	"  .defaultSkin span.mce_underline::before { content: \"\\f0cd\"; color: #333 !important; font-size: 16px !important; width: 20px !important; height: 20px !important; }",
	"  .defaultSkin span.mce_strikethrough { background-position: unset !important; text-align: center !important; }",
	"  .defaultSkin span.mce_strikethrough::before { content: \"\\f0cc\"; color: #333 !important; font-size: 16px !important; width: 20px !important; height: 20px !important; }",
	"  .defaultSkin span.mce_indent { background-position: unset !important; text-align: center !important; }",
	"  .defaultSkin span.mce_indent::before { content: \"\\f03c\"; color: #333 !important; font-size: 16px !important; width: 20px !important; height: 20px !important; }",
	"  .defaultSkin span.mce_outdent { background-position: unset !important; text-align: center !important; }",
	"  .defaultSkin span.mce_outdent::before { content: \"\\f03b\"; color: #333 !important; font-size: 16px !important; width: 20px !important; height: 20px !important; }",
	"  .defaultSkin span.mce_bullist { background-position: unset !important; text-align: center !important; }",
	"  .defaultSkin span.mce_bullist::before { content: \"\\f0ca\"; color: #333 !important; font-size: 16px !important; width: 20px !important; height: 20px !important; }",
	"  .defaultSkin span.mce_numlist { background-position: unset !important; text-align: center !important; }",
	"  .defaultSkin span.mce_numlist::before { content: \"\\f0cb\"; color: #333 !important; font-size: 16px !important; width: 20px !important; height: 20px !important; }",
	"  .defaultSkin span.mce_table { background-position: unset !important; text-align: center !important; }",
	"  .defaultSkin span.mce_table::before { content: \"\\f0ce\"; color: #333 !important; font-size: 16px !important; width: 20px !important; height: 20px !important; }",
	"  .defaultSkin span.mce_link { background-position: unset !important; text-align: center !important; }",
	"  .defaultSkin span.mce_link::before { content: \"\\f0c1\"; color: #333 !important; font-size: 16px !important; width: 20px !important; height: 20px !important; }",
	"  .defaultSkin span.mce_unlink { background-position: unset !important; text-align: center !important; }",
	"  .defaultSkin span.mce_unlink::before { content: \"\\f127\"; color: #333 !important; font-size: 16px !important; width: 20px !important; height: 20px !important; }",
	"  .defaultSkin span.mce_insertmedia { background-position: unset !important; text-align: center !important; }",
	"  .defaultSkin span.mce_insertmedia::before { content: \"\\f0c6\"; color: #333 !important; font-size: 16px !important; width: 20px !important; height: 20px !important; }",
	"  .defaultSkin span.mce_image { background-position: unset !important; text-align: center !important; }",
	"  .defaultSkin span.mce_image::before { content: \"\\f03e\"; color: #333 !important; font-size: 16px !important; width: 20px !important; height: 20px !important; }",
	"  .defaultSkin span.mce_smilies { background-position: unset !important; text-align: center !important; }",
	"  .defaultSkin span.mce_smilies::before { content: \"\\f118\"; color: #333 !important; font-size: 16px !important; width: 20px !important; height: 20px !important; }",
	"  .defaultSkin span.mce_forecolor::before { font-size: 16px !important; text-align: center !important; }",
	"  .defaultSkin span.mce_backcolor::before { font-size: 16px !important; text-align: center !important; }",
	"  .defaultSkin a.mceButtonEnabled:hover { background-color: rgba(255, 255, 255, 0.9) !important; border: 1px outset #ccc !important; }",
	"  .defaultSkin a.mceButtonActive, .defaultSkin a.mceButtonSelected { background-color: rgba(0, 0, 0, 0.1) !important; border: 1px inset #ccc !important; }",
	"  .defaultSkin .mceSplitButton a.mceAction { border: 1px solid transparent !important; }",
	"  .defaultSkin .mceSplitButton a.mceOpen { border: 1px solid transparent !important; }",
	"  .defaultSkin table.mceSplitButtonEnabled:hover a.mceAction, .defaultSkin .mceSplitButtonHover a.mceAction, .defaultSkin .mceSplitButtonSelected a.mceAction { background-color: rgba(255, 255, 255, 0.9) !important; border: 1px outset #ccc !important; }",
	"  .defaultSkin table.mceSplitButtonEnabled:hover a.mceOpen, .defaultSkin .mceSplitButtonHover a.mceOpen, .defaultSkin .mceSplitButtonSelected a.mceOpen { background-color: rgba(255, 255, 255, 0.9) !important; border: 1px outset #ccc !important; }",
	"  .defaultSkin .mceSplitButtonActive a.mceAction { background-color: rgba(255, 255, 255, 0.9) !important; border: 1px outset #ccc !important; }",
	"  form#aspnetForm > div:last-child { box-shadow: 0 2px 2px 0 rgba(0, 0, 0, 0.14), 0 3px 1px -2px rgba(0, 0, 0, 0.2), 0 1px 5px 0 rgba(0, 0, 0, 0.12); }",
	"  .CommonContextMenuGroup { background-color: #fcf7f2; }",
	"  .CommonContextMenuItem { background-color: #fcf7f2; border: solid 1px #fcf7f2; padding: 8px; }",
	"  .CommonContextMenuItemHover { background-color: #f8e8d7; border: solid 1px #e1e1e1; color: black; padding: 8px; }",
	"  #navInfo ul, #navSites ul { padding: 0; }",
	"  #navInfo li, #navSites li { margin: 0 0.1em; padding: 0; }",
	"  #navInfo li.current, #navSites li.current { color: #626262; text-decoration: none; }",
	"  #navInfo a, #navSites a, #subHeader a { padding: 0.3em 0.7em; border-radius: 5px; color: #005ec4; text-decoration: none; transition: background-color 200ms ease-in-out; }",
	"  #navInfo .current a:link, #navSites .current a:visited, #navSites .current a { color: #626262; text-decoration: none; }",
	"  #navInfo a:hover, #navSites a:hover, #subHeader a:hover { color: #005ec4; background-color: #d7e7f8; }",
	"  #navInfo .current a:hover, #navSites .current a:hover { text-decoration: none; background-color: transparent; }",
	"  #CommonHeaderUserContent { padding: 0; }",
	"  #CommonHeaderUserArea a:link, #CommonHeaderUserArea a:visited { border: 1px solid #005ec4; color: #005ec4; font-weight: 500; letter-spacing: 1px; padding: 0.25em 1em; border-radius: 5px; text-decoration: none; transition: background-color 200ms ease-in-out; }",
	"  #CommonHeaderUserArea a:hover { text-decoration: none; background-color: #d7e7f8; }",
	"  #CommonHeaderUserWelcome .sub:not(:last-child) { color: transparent; }",
	"  #CommonHeaderUserWelcome .sub a:link, #CommonHeaderUserWelcome .sub a:visited { padding: 0.3em 0.7em; border: none; color: #005ec4; font-weight: normal; letter-spacing: 0; text-decoration: none; }",
	"  #CommonHeaderUserWelcome .sub a:hover { background-color: #d7e7f8; color: #005ec4; text-decoration: none; border-radius: 5px; }",
	"  #CommonHeaderUserWelcome .sub a[href*=\"EditProfile.aspx\"]::before { -webkit-font-smoothing: antialiased; -moz-osx-font-smoothing: grayscale; display: inline-block; font-style: normal; font-variant: normal; font-weight: normal; line-height: 1; vertical-align: -.125em; content: \"\\f303\"; font-size: 14px; margin-right: 0.3em; }",
	"  #CommonHeaderUserWelcome .sub a[href$=\"logout.aspx\"]::before { -webkit-font-smoothing: antialiased; -moz-osx-font-smoothing: grayscale; display: inline-block; font-style: normal; font-variant: normal; font-weight: normal; line-height: 1; vertical-align: -.125em; content: \"\\f011\"; font-size: 14px; margin-right: 0.3em; }",
	"  .CommonSearchArea, .CommonSearchAreaSidebar { width: 460px; }",
	"  .CommonSearchContent, .CommonSearchContentSidebar { position: relative; height: 2.5em; width: 100%; margin: 0; padding: 0; border: none; }",
	"  .CommonSearchContentInner { position: relative; top: 0; left: 0; height: 100%; width: 100%; }",
	"  .CommonSearchContent input, .CommonSearchContentSidebar input { box-sizing: border-box; position: absolute; margin: 0; padding: 0 5em 0 1em; height: 100%; width: 100%; border: 1px solid #c3c3c3; background-color: #f4f4f4; color: #c3c3c3; font-size: 16px; letter-spacing: .02em; }",
	"  .CommonSearchContent input::-ms-clear, .CommonSearchContentSidebar input::-ms-clear { display: none !important; }",
	"  .CommonSearchContent input:focus, .CommonSearchContent input:focus, .CommonSearchContentSidebar input:focus, .CommonSearchContentSidebar input:focus { border: none; outline: none; box-shadow: inset 0px 0px 3px 1px #005ec4; color: #626262; }",
	"  .CommonSearchContent input.CommonSearchButton, .CommonSearchContent input.CommonSearchButtonSideBar, .CommonSearchContentSidebar input.CommonSearchButton, .CommonSearchContentSidebar input.CommonSearchButtonSideBar { position: absolute; right: 0; top: 0; width: 50px; height: 100%; margin: 0; padding: 0; background-color: transparent; background-position: center; background-repeat: no-repeat; overflow: hidden; border: none; cursor: pointer; }",
	"  #ctl00_bcr_MediaTabs_TabSet.CommonPaneTabSet { Background-color: #c3c3c3; }",
	"  #ctl00_bcr_MediaTabs_TabSet.CommonPaneTabSet .CommonPaneTab, #ctl00_bcr_MediaTabs_TabSet.CommonPaneTabSet .CommonPaneTabHover, #ctl00_bcr_MediaTabs_TabSet.CommonPaneTabSet .CommonPaneTabSelected { text-decoration: none; background-color: #ddd; margin: 0; padding: 0; padding: .5em 1em; margin: .5em .5em 0 0; border-top-left-radius: 2px; border-top-right-radius: 2px; }",
	"  #ctl00_bcr_MediaTabs_TabSet.CommonPaneTabSet .CommonPaneTabHover { background-color: #eee; }",
	"  #ctl00_bcr_MediaTabs_TabSet.CommonPaneTabSet .CommonPaneTabSelected { background-color: #fff; }",
	"  #ctl00_ctl00_bcr_bcr_PostForm_ctl05_EditorTabs_TabSet.CommonPaneTabSet { width: 70%; border-bottom: 4px solid #e39c4f; }",
	"  #ctl00_ctl00_bcr_bcr_PostForm_ctl05_EditorTabs_TabSet.CommonPaneTabSet > div > table { display: inline; }",
	"  #ctl00_ctl00_bcr_bcr_PostForm_ctl05_EditorTabs_TabSet.CommonPaneTabSet a.CommonPaneTab, #ctl00_ctl00_bcr_bcr_PostForm_ctl05_EditorTabs_TabSet.CommonPaneTabSet a.CommonPaneTabHover, #ctl00_ctl00_bcr_bcr_PostForm_ctl05_EditorTabs_TabSet.CommonPaneTabSet a.CommonPaneTabSelected { display: inline-block; padding: .5em 1em; margin: .5em .5em 0 0; border-top-left-radius: 2px; border-top-right-radius: 2px; transform: scale(0.95); transform-origin: bottom; }",
	"  #ctl00_ctl00_bcr_bcr_PostForm_ctl05_EditorTabs_TabSet.CommonPaneTabSet a.CommonPaneTab { background: linear-gradient(to bottom, silver 0%, #a0a0a0 80%, #909090 100%); }",
	"  #ctl00_ctl00_bcr_bcr_PostForm_ctl05_EditorTabs_TabSet.CommonPaneTabSet a.CommonPaneTabHover { background: none; background-color: #f8e8d7; }",
	"  #ctl00_ctl00_bcr_bcr_PostForm_ctl05_EditorTabs_TabSet.CommonPaneTabSet a.CommonPaneTabHover .TabButton { font-weight: 500; }",
	"  #ctl00_ctl00_bcr_bcr_PostForm_ctl05_EditorTabs_TabSet.CommonPaneTabSet a.CommonPaneTabSelected { background: none; background-color: #e39c4f; transform: scale(1); }",
	"  #ctl00_ctl00_bcr_bcr_PostForm_ctl05_EditorTabs_TabSet.CommonPaneTabSet a.CommonPaneTabSelected .TabButton { font-weight: 700; }",
	"  #ctl00_ctl00_bcr_bcr_PostForm_ctl05_EditorTabs_TabSet.CommonPaneTabSet .TabButton { background-image: none; background-color: transparent; color: #333; text-decoration: none; font-weight: 400; }",
	"  .CommonCommentArea { box-shadow: 0 2px 2px 0 rgba(0, 0, 0, 0.14), 0 3px 1px -2px rgba(0, 0, 0, 0.2), 0 1px 5px 0 rgba(0, 0, 0, 0.12); background-color: #d7e7f8; margin: 10px 0; }",
	"  .CommonCommentContent { background-color: #f2f7fc !important; border-left: 2px solid #005ec4; padding: 10px; }",
	"  .CommonCommentAreaAlt { box-shadow: 0 2px 2px 0 rgba(0, 0, 0, 0.14), 0 3px 1px -2px rgba(0, 0, 0, 0.2), 0 1px 5px 0 rgba(0, 0, 0, 0.12); background-color: #f8e8d7; margin: 10px 0; }",
	"  .CommonCommentContentAlt { background-color: #fcf7f2 !important; border-left: 2px solid #005ec4; padding: 10px; }",
	"  .CommonCommentContent > div, .CommonCommentContentAlt > div { min-height: 110px; }",
	"  .CommonCommentContent blockquote, .CommonCommentContentAlt blockquote { background-color: rgba(0, 0, 0, 0.03); box-shadow: none; margin: 1em 2em 1em 1.5em; padding: .5em 1em 1em 1em; border: none; border-top: 1px solid #005ec4; border-right: 1px solid #005ec4; border-radius: 0; }",
	"  .CommonCommentContent blockquote div:first-of-type > img:first-of-type, .CommonCommentContentAlt blockquote div:first-of-type > img:first-of-type { display: none; }",
	"  .CommonCommentContent blockquote div:first-of-type > img:first-of-type + strong, .CommonCommentContentAlt blockquote div:first-of-type > img:first-of-type + strong { position: relative; top: -1em; }",
	"  .CommonCommentContent blockquote div:first-of-type > img:first-of-type + strong:before, .CommonCommentContentAlt blockquote div:first-of-type > img:first-of-type + strong:before { display: inline-block; position: relative; left: -.1em; top: .25em; content: open-quote; font-family: \"Times New Roman\", Times, serif; font-weight: 700; font-size: 3em; color: #005ec4; height: 1em; }",
	"  body.forceColors #insert, body.forceColors #cancel, body.forceColors input, body#image #insert, body#image #cancel, body#image .mceActionPanel input, .CommonPane input[type=\'submit\'] { background-image: none; background-color: #fcf7f2; color: #666; border-radius: 4px; border: 1px solid  #666; }",
	"  body.forceColors #insert:hover, body.forceColors #cancel:hover, body.forceColors input:hover, body#image #insert:hover, body#image #cancel:hover, body#image .mceActionPanel input:hover, .CommonPane input:hover[type=\'submit\'], body.forceColors #insert:focus, body.forceColors #cancel:focus, body.forceColors input:focus, body#image #insert:focus, body#image #cancel:focus, body#image .mceActionPanel input:focus, .CommonPane input:focus[type=\'submit\'] { color: #000; border-color: #000; }",
	"  .CommonModal { box-shadow: 0 9px 46px 8px rgba(0, 0, 0, 0.14), 0 11px 15px -7px rgba(0, 0, 0, 0.12), 0 24px 38px 3px rgba(0, 0, 0, 0.2); background-color: #f4f4f4; border: solid 3px #ccc; }",
	"  .CommonModal .CommonModalTitle { background-color: #f4f4f4; border: none; }",
	"  .CommonModalFooter { height: 18px; }",
	"  .CommonModalResize { right: 4px; bottom: 4px; }",
	"  form[action*=\"QuickReply.aspx\"] #CommonOuter { box-shadow: 0 9px 46px 8px rgba(0, 0, 0, 0.14), 0 11px 15px -7px rgba(0, 0, 0, 0.12), 0 24px 38px 3px rgba(0, 0, 0, 0.2); }",
	"  form[action*=\"QuickReply.aspx\"] .CommonFormFieldName > label { color: #e39c4f; }",
	"  #ctl00_ctl00_bcr_bcr_PostForm_ctl05_EditorTabs { background-color: #626262; margin: 0; padding: 0; }",
	"  .ForumReplyToPostArea { background-color: rgba(0, 0, 0, 0.05); box-shadow: none; margin: 1em 0; padding: .5em 1em 1em 1em; border: none; border-top: 1px solid #005ec4; border-right: 1px solid #005ec4; border-radius: 0; }",
	"  .ForumReplyToPostArea .CommonTextButton { margin: 0; padding: 0; }",
	"  .ForumReplyToPostArea + .CommonFormArea > .CommonFormFieldName { color: #e39c4f; }",
	"  #ctl00_ctl00_bcr_bcr_PostForm_ctl05_OptionsPane > .CommonFormFieldName > label { color: #e39c4f; }",
	"  .CommonContentBoxHeaderForm .CommonContentBoxHeaderInline a { text-shadow: 0 2px 2px rgba(0, 0, 0, 0.14); }",
	"  .CommonFormArea { background-color: #626262; padding: 5px; }",
	"  html:not([xmlns=\"http://www.w3.org/1999/xhtml\"]) { background: white; }",
	"  .mceContentBody { background-color: white; }",
	"  .CommonFormField label { color: #e39c4f; letter-spacing: .25px; }",
	"  div.CommonFormFieldPadding { padding: 5px 10px 10px 10px; }",
	"  body.forceColors { background-color: #c3c3c3; }",
	"  body.forceColors #insert, body.forceColors #cancel, body.forceColors input { margin: 0; }",
	"  body.forceColors textarea { margin: .25em 0 0 0; padding: .5em; background-color: #fff; }",
	"  body#image .panel_wrapper { height: 224px; }",
	"  body#image .CommonModal { background-color: #c3c3c3; }",
	"  body#image #src, body#image #alt { width: 160px !important; }",
	"  body#image #insert, body#image #cancel, body#image .mceActionPanel input { margin-bottom: 8px; }",
	"  .CommonPane input[value=\'cancel\'] { float: right; }",
	"  .CommonContentBoxHeaderInline { color: #fff; text-shadow: 0 2px 2px rgba(0, 0, 0, 0.14); letter-spacing: .02em; }",
	"  .CommonAvatarListArea { box-shadow: 0 2px 2px 0 rgba(0, 0, 0, 0.14), 0 3px 1px -2px rgba(0, 0, 0, 0.2), 0 1px 5px 0 rgba(0, 0, 0, 0.12); background: #d7e7f8; width: 76px; margin: 8px; padding: 12px; border-radius: 8px; }",
	"  .CommonAvatarListArea .CommonAvatarArea { width: 76px; height: 76px; margin-bottom: 8px; box-shadow: 0 2px 2px 0 rgba(0, 0, 0, 0.14), 0 3px 1px -2px rgba(0, 0, 0, 0.2), 0 3px 5px 0 rgba(0, 0, 0, 0.12); }",
	"  .CommonAvatarListArea .CommonAvatarArea img { width: 98% !important; height: 98% !important; }",
	"  .CommonAvatarListArea > a { font-weight: 700 !important; letter-spacing: .025em; }",
	"  form[action*=\"a908d13f-b28a-41d9-ad6f-a58d54987218\"] .CommonAvatarListArea { background: #ceecc1; }",
	"  form[action*=\"6388d75f-2687-441f-a94e-e966f273121e\"] .CommonContentBoxHeaderInline { position: relative; color: transparent; text-shadow: none; }",
	"  form[action*=\"6388d75f-2687-441f-a94e-e966f273121e\"] .CommonContentBoxHeaderInline::before { display: inline-block; position: absolute; color: #fff; text-shadow: 0 2px 2px rgba(0, 0, 0, 0.14); content: \'I have fought the good fight, I have finished the race, I have kept the faith. (2 Ti 4:7)\'; }",
	"  form[action*=\"6388d75f-2687-441f-a94e-e966f273121e\"] .CommonAvatarListArea { background: #fff; }",
	"  form[action$=\"6388d75f-2687-441f-a94e-e966f273121e\"]::after { box-shadow: 0 9px 46px 8px rgba(0, 0, 0, 0.14), 0 11px 15px -7px rgba(0, 0, 0, 0.12), 0 24px 38px 3px rgba(0, 0, 0, 0.2); display: inline-block; position: fixed; margin: 0; padding: 1em 2em; border-radius: .5em; left: 16%; bottom: 5em; width: calc(100Vw - 40%); background: lightgoldenrodyellow; color: darkgoldenrod; font-weight: 500; letter-spacing: .05em; font-size: 1.2em; content: \'For I know that my Redeemer lives, and at the last he will stand upon the earth. And after my skin has been thus destroyed, yet in my flesh I shall see God, whom I shall see for myself, and my eyes shall behold, and not another. My heart faints within me! (Job 19:25-27)\'; white-space: normal; z-index: 1000; }",
	"  #CommonHeader { box-shadow: 0 2px 2px 0 rgba(0, 0, 0, 0.14), 0 3px 1px -2px rgba(0, 0, 0, 0.2), 0 1px 5px 0 rgba(0, 0, 0, 0.12); background-color: #f4f4f4; padding-top: .75em; }",
	"  #CommonHeaderTitleArea { width: 970px; height: 60px; }",
	"  #CommonHeaderTitleArea table { table-layout: fixed; }",
	"  #CommonHeaderTitleArea table tr { vertical-align: middle; }",
	"  #CommonHeaderTitleArea table tr td:first-child { width: 500px; }",
	"  #CommonHeaderTitleArea table tr td:first-child a { display: inline-block; background-image: url(https://styles2.faithlifecdn.com/Content/Images/faithlife-logo.svg); background-size: cover; width: 180px; height: 52px; }",
	"  #CommonHeaderTitleArea table tr td:first-child a::after { content: \"Community\"; color: #666666; font-family: \"Source Sans Pro\", sans-serif; font-size: 44px; font-weight: 300; position: relative; left: 190px; }",
	"  #CommonHeaderTitleArea table tr td:first-child a:hover { text-decoration: none; filter: drop-shadow(0px 0px 2px rgba(95, 188, 57, 0.7)); }",
	"  #CommonHeaderTitleArea table img { display: none; }",
	"  #CommonNavigationShadow { visibility: hidden; display: inline; }",
	"  form[action^=\"/search/SearchResults.aspx\"] .Common { box-shadow: none !important; }",
	"  form[action^=\"/search/SearchResults.aspx\"] #ctl00_bcr_ctl00_ctl00_SearchTextTop { height: 1.8em; width: 90%; padding: .25em .75em; border: 1px solid #777; color: #333; font-weight: 400; font-size: 100%; letter-spacing: .05em; }",
	"  form[action^=\"/search/SearchResults.aspx\"] #ctl00_bcr_ctl00_ctl00_SearchTextTop + span:nth-of-type(2)::before { content: \' \\A\'; white-space: pre; }",
	"  form[action^=\"/search/SearchResults.aspx\"] #ctl00_bcr_ctl00_ctl00_SearchButtonTop { width: auto !important; margin-left: 12px; }",
	"  form[action^=\"/search/SearchResults.aspx\"] .CommonAvatarListItemArea { box-shadow: 0 2px 2px 0 rgba(0, 0, 0, 0.14), 0 3px 1px -2px rgba(0, 0, 0, 0.2), 0 1px 5px 0 rgba(0, 0, 0, 0.12); background-color: #f4f7fa; color: black; }",
	"  form[action^=\"/search/SearchResults.aspx\"] .CommonAvatarListItemArea.Alt { box-shadow: 0 2px 2px 0 rgba(0, 0, 0, 0.14), 0 3px 1px -2px rgba(0, 0, 0, 0.2), 0 1px 5px 0 rgba(0, 0, 0, 0.12); background-color: #faf7f4; color: black; }",
	"  #CommonSidebarLeft .CommonContentBoxHeader, #CommonSidebarRight .CommonContentBoxHeader { background-image: none; padding: 0; margin: 8px; border-bottom: 1px solid #e39c4f; color: #e39c4f; text-shadow: 0 2px 2px rgba(0, 0, 0, 0.14); }",
	"  #CommonSidebarLeft .CommonContentBox, #CommonSidebarRight .CommonContentBox { padding: 5px; }",
	"  #CommonSidebarLeft ul.CommonContentBoxList a, #CommonSidebarRight ul.CommonContentBoxList a { color: #f8e8d7; }",
	"  #CommonSidebarLeft .CommonContentBoxContent { color: #f8e8d7; margin: 0; padding: 10px; display: flex !important; flex-flow: column nowrap; align-items: center; }",
	"  #CommonSidebarLeft .CommonContentBoxContent div { float: none !important; margin: 0 !important; display: flex; flex-flow: column; align-items: center; }",
	"  #CommonSidebarLeft .CommonContentBoxContent div img { box-shadow: 0 2px 2px 0 rgba(0, 0, 0, 0.14), 0 3px 1px -2px rgba(0, 0, 0, 0.2), 0 1px 5px 0 rgba(0, 0, 0, 0.12); max-width: 100%; width: 100% !important; height: auto !important; margin-bottom: 10px; border-radius: 8px; }",
	"  #CommonSidebarLeft .CommonContentBoxContent div div { display: block; }",
	"  #CommonSidebarLeft .CommonContentBoxContent a { color: #e39c4f; }",
	"  ul.CommonContentBoxList, ul.CommonSidebarList a { color: #f8e8d7; }",
	"  form[action^=\"/forums/ForumSubscriptions.aspx\"] h2.CommonListTitle::after { font-weight: 400; font-size: 60%; content: \"(Select \\2714 or \\2718 to toggle forum subscriptions on or off.)\"; margin-left: 1em; }",
	"  form[action^=\"/forums/ForumSubscriptions.aspx\"] .CommonListHeader:nth-of-type(2) { text-align: center; }",
	"  form[action^=\"/forums/ForumSubscriptions.aspx\"] .CommonListArea { background: #fff; padding: 1em; }",
	"  form[action^=\"/forums/ForumSubscriptions.aspx\"] .CommonListArea table { border-top: 1px solid #ccc; border-left: 1px solid #ccc; }",
	"  form[action^=\"/forums/ForumSubscriptions.aspx\"] .CommonListCell a[id$=\"_off\"], form[action^=\"/forums/ForumSubscriptions.aspx\"] .CommonListCell a[id$=\"_on\"], form[action^=\"/forums/ForumSubscriptions.aspx\"] .CommonListCell a[id$=\"_processing\"] { color: transparent; }",
	"  form[action^=\"/forums/ForumSubscriptions.aspx\"] .CommonListCell a[id$=\"_off\"]::before, form[action^=\"/forums/ForumSubscriptions.aspx\"] .CommonListCell a[id$=\"_on\"]::before, form[action^=\"/forums/ForumSubscriptions.aspx\"] .CommonListCell a[id$=\"_processing\"]::before { font-size: 120%; font-weight: 700; color: #333; }",
	"  form[action^=\"/forums/ForumSubscriptions.aspx\"] .CommonListCell a[id$=\"_off\"]::before { content: \"\\2718\"; }",
	"  form[action^=\"/forums/ForumSubscriptions.aspx\"] .CommonListCell a[id$=\"_on\"]::before { content: \"\\2714\"; }",
	"  form[action^=\"/forums/ForumSubscriptions.aspx\"] .CommonListCell a[id$=\"_processing\"]::before { content: \"\\2026\"; }",
	"  h1.CommonTitle { font-variant: small-caps; font-size: 200%; font-weight: 500; color: black; }",
	"  .CommonContentBox { background-color: #626262; border-radius: 10px; padding: 8px 8px 2px 8px !important; }",
	"  #CommonContent .CommonContentBoxHeader { background-image: none; color: #e39c4f; margin: 0; padding: 10px 10px 0 10px; text-shadow: 0 2px 2px rgba(0, 0, 0, 0.14); }",
	"  .CommonContentBoxHeaderForm { box-shadow: 0 2px 2px 0 rgba(0, 0, 0, 0.14), 0 3px 1px -2px rgba(0, 0, 0, 0.2), 0 1px 5px 0 rgba(0, 0, 0, 0.12); background-image: none; margin: 10px 10px 0 10px; border: 1px outset #f4f4f4; border-radius: 8px; padding: 8px 12px 4px 12px; color: #f4f4f4; }",
	"  .CommonContentBoxHeaderForm a { color: #e39c4f; }",
	"  .CommonContentBoxHeaderForm a.ForumLinkUnread, .CommonContentBoxHeaderForm .ForumLinkUnread:link, .CommonContentBoxHeaderForm .ForumLinkUnread:visited { color: #e39c4f; }",
	"  .CommonContentBoxContent { padding: 10px; }",
	"  .CommonContentBoxContent table a { color: #e39c4f; }",
	"  .CommonContentBoxContent .ForumPostButtons a { color: #c46600; }",
	"  .CommonListArea { box-shadow: 0 2px 2px 0 rgba(0, 0, 0, 0.14), 0 3px 1px -2px rgba(0, 0, 0, 0.2), 0 1px 5px 0 rgba(0, 0, 0, 0.12); padding: 2px 0; }",
	"  .CommonListArea table a { color: #056cb6; }",
	"  .CommonListHeader { color: black; background-color: #f4f4f4 !important; font-family: -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, Oxygen-Sans, Ubuntu, Cantarell, \"Helvetica Neue\", sans-serif; }",
	"  .CommonListRow td, .CommonListRowAlt td { background-color: transparent; }",
	"  .CommonListRow { background-color: #f4f7fa; }",
	"  .CommonListRow:hover { background-color: rgba(244, 247, 250, 0.9); }",
	"  .CommonListRowAlt { background-color: #f7f7f7; }",
	"  .CommonListRowAlt:hover { background-color: rgba(247, 247, 247, 0.9); }",
	"  .CommonListCell { font-family: -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, Oxygen-Sans, Ubuntu, Cantarell, \"Helvetica Neue\", sans-serif; color: #333; padding: 10px; }",
	"  .ForumPostHeader { box-shadow: 0 2px 2px 0 rgba(0, 0, 0, 0.14), 0 3px 1px -2px rgba(0, 0, 0, 0.2), 0 1px 5px 0 rgba(0, 0, 0, 0.12); background-color: #f4f4f4; border: none; border-radius: 8px; margin: 10px 0; }",
	"  .ForumPostHeader .CommonContentBoxFooter { color: Black; font-weight: normal; }",
	"  .ForumPostHeader .CommonContentBoxFooter a:link, .ForumPostHeader .CommonContentBoxFooter a:visited, .ForumPostHeader .CommonContentBoxFooter a:active, .ForumPostHeader .CommonContentBoxFooter a:hover { color: #c46600; font-weight: 500; letter-spacing: .5px; }",
	"  .CommonContentBoxFooter { padding: 0 10px 10px 10px; border-top: none; color: #f4f4f4; }",
	"  .CommonContentBoxFooter a:link, .CommonContentBoxFooter a:visited { color: #e39c4f; }",
	"  h4.CommonAvatarListItemName ~ .CommonFormArea { display: none; }",
	"  a.ForumGroupNameReadText, a.ForumGroupNameUnReadText, .ForumGroupNameReadText:link, .ForumGroupNameUnReadText:link, .ForumGroupNameReadText:visited, .ForumGroupNameUnReadText:visited { color: #005ec4; padding-left: 12px; }",
	"  .CommonListArea table a { color: #005ec4; }",
	"  a.ForumNameUnRead, .ForumNameUnRead:link, .ForumNameUnRead:visited { color: #005ec4; font-weight: bold; }",
	"  a.ForumNameRead, .ForumNameRead:link, .ForumNameRead:visited { color: #626262; }",
	"  .CommonDescription { color: #fcf7f2; margin: 8px 0 4px 0 !important; }",
	"  #CommonSidebarLeft ul.CommonContentBoxList a[href=\"https://faithlife.com/account/edit\"] { border-top: 1px dashed #f8e8d7; padding-top: 2px; position: relative; top: 12px; font-size: 8pt; font-weight: normal; }",
	"  h4.CommonContentBoxHeader + .CommonContentBoxContent { color: white; }",
	"  ul.CommonContentBoxList li.Header { color: white; font-weight: normal; }",
	"  ul.CommonContentBoxList li.CommonActivity { color: white; }",
	"  ul.CommonContentBoxList li.CommonActivity table a img { display: none; }",
	"  ul.CommonContentBoxList li.CommonActivity table tr td + td a::after { -webkit-font-smoothing: antialiased; -moz-osx-font-smoothing: grayscale; display: inline-block; font-style: normal; font-variant: normal; font-weight: normal; line-height: 1; vertical-align: -.125em; content: \"\\f2ed\"; font-size: 16px; color: #e39c4f; }",
	"  ul.CommonContentBoxList li.CommonActivity table tr td + td a:hover { text-decoration: none; }",
	"  ul.CommonContentBoxList li.CommonActivity.NewForumThread { background-image: none; }",
	"  ul.CommonContentBoxList li.CommonActivity.NewForumThread td:first-child::before { -webkit-font-smoothing: antialiased; -moz-osx-font-smoothing: grayscale; display: inline-block; font-style: normal; font-variant: normal; font-weight: normal; line-height: 1; vertical-align: -.125em; content: \"\\f0e0\"; font-size: 18px; color: #e39c4f; margin-right: .5em; }",
	"  ul.CommonContentBoxList li.CommonActivity.NewForumPost { background-image: none; }",
	"  ul.CommonContentBoxList li.CommonActivity.NewForumPost td:first-child::before { -webkit-font-smoothing: antialiased; -moz-osx-font-smoothing: grayscale; display: inline-block; font-style: normal; font-variant: normal; font-weight: normal; line-height: 1; vertical-align: -.125em; content: \"\\f3e5\"; font-size: 18px; color: #e39c4f; margin-right: .5em; }",
	"  .CommonGroupedContentArea { box-shadow: 0 2px 2px 0 rgba(0, 0, 0, 0.14), 0 3px 1px -2px rgba(0, 0, 0, 0.2), 0 1px 5px 0 rgba(0, 0, 0, 0.12); background-color: #fcf7f2; border-radius: 8px; padding: 10px 10px 20px 10px; }",
	"  .CommonGroupedContentArea h3.CommonSubTitle { color: #c46600; margin-top: 5px; }",
	"  .CommonGroupedContentArea .CommonFormFieldDescription { color: black; }",
	"  .CommonGroupedContentArea .CommonFormFieldDescription a:link, .CommonGroupedContentArea .CommonFormFieldDescription a:visited, .CommonGroupedContentArea .CommonFormFieldDescription a:active, .CommonGroupedContentArea .CommonFormFieldDescription a:hover { color: #c46600; }",
	"  .CommonGroupedContentArea div.CommonFormFieldName { color: black; padding: 2px; }",
	"  .CommonGroupedContentArea td.CommonFormFieldName { height: 2em; }",
	"  .CommonGroupedContentArea .CommonFormField label { color: black; }",
	"  .CommonGroupedContentArea .CommonFormField label:not(:first-child) { margin-left: 12px; }"
].join("\n");
if (typeof GM_addStyle != "undefined") {
	GM_addStyle(css);
} else if (typeof PRO_addStyle != "undefined") {
	PRO_addStyle(css);
} else if (typeof addStyle != "undefined") {
	addStyle(css);
} else {
	var node = document.createElement("style");
	node.type = "text/css";
	node.appendChild(document.createTextNode(css));
	var heads = document.getElementsByTagName("head");
	if (heads.length > 0) {
		heads[0].appendChild(node);
	} else {
		// no head yet, stick it whereever
		document.documentElement.appendChild(node);
	}
}
})();
